### ISSUE TITLE
HR result is not similar to source image.

### ISSUE THREAD

**Issue by gordinmitya** [adamian98/pulse#1]
Thank you for your impressive work and for sharing the code.
I put two png images into `input` folder:

| size | 256x256   |      32x32      |
|----------|----------|-------------|
| input |  ![2020-06-02 14 36 43](https://user-images.githubusercontent.com/9286092/83515844-ae2b7500-a4de-11ea-8e5d-ee341e67f989.jpg)|  ![selfie](https://user-images.githubusercontent.com/9286092/83516062-124e3900-a4df-11ea-8fe2-a2c34702c3df.png) |
| result | <img src="https://user-images.githubusercontent.com/9286092/83516470-cbad0e80-a4df-11ea-92be-a841e1b1975a.jpeg" width=256 height=256/> | <img src="https://user-images.githubusercontent.com/9286092/83516493-d23b8600-a4df-11ea-80f8-1e274c63b838.jpeg" width=256 height=256/> |

Moreover if I downscale enhanced image back to 32x32 I got very different thumbnail from the original one:
<img  alt="Screenshot 2020-06-02 at 2 50 51 PM" src="https://user-images.githubusercontent.com/9286092/83516825-76253180-a4e0-11ea-8c7f-e40d85a4821f.png">

Could you assist me what am I doing wrong and how to reproduce results from paper?

**Comment by sachit-menon** [comment]
Hi, I suspect it may have to do with the input resolution you're using. What scale factor are you set to? Here are the results I get with the default x32 scaling (after bicubically upscaling the 256x256 image to 1024x1024) using the [Colab](https://colab.research.google.com/drive/1-cyGV0FoSrHcQSVq3gKOymGTMt0g63Xc?usp=sharing#sandboxMode=true), an easy way to verify your results: 
![image](https://user-images.githubusercontent.com/21482705/83708915-65151700-a5eb-11ea-8eff-672d14dc3978.png)

Let me know if you have further issues. I'll be uploading a ReadME with instructions on how to use the code in the next 1-2 days that may clarify some things.

**Comment by sachit-menon** [comment]
I've uploaded the README that hopefully addresses some of your questions, please give it a look. If you use the `align_face.py` script your problem should go away and you should get similar results to the Colab (image in my previous comment).
