### ISSUE TITLE
output not similar to the input

### ISSUE THREAD

**Issue by xiaohaipeng** [adamian98/pulse#10]
with several pics from FFHQ dataset,i  used align_face.py to downsample 32X, and runned run.py, the output pics were not the same person as inputs,why?
![00000](https://user-images.githubusercontent.com/30681655/85022766-53646f80-b1a6-11ea-9a3c-a65b1cf21d06.png)
![00000_0](https://user-images.githubusercontent.com/30681655/85022879-798a0f80-b1a6-11ea-9f24-449a88dc6c4c.png)
![00000_0](https://user-images.githubusercontent.com/30681655/85022933-97f00b00-b1a6-11ea-994c-b23311602dec.png)

**Comment by davidanger** [comment]
Model not for child ........

**Comment by limitmhw** [comment]
I have using the stylegan2-encoder to generate a  new face,and i find the output not similar to the input

**Comment by radarxc** [comment]
Is there any to train model and use custom model?

**Comment by xjohnxjohn** [comment]
> Is there any way to train custom model and use custom model?

Do you have the solutions now?

**Comment by radarxc** [comment]
> > Is there any way to train custom model and use custom model?
> 
> Do you have the solutions now?

No lucky. I am still waiting for more detail in future documentation.
