### ISSUE TITLE
CUDA Out of memory with 2 GB of VRAM

### ISSUE THREAD

**Issue by AlbyTree** [adamian98/pulse#11]
If I try to use the pre-trained model I get this error

`RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 1.95 GiB total capacity; 1.19 GiB already allocated; 57.31 MiB free; 1.25 GiB reserved in total by PyTorch)`  

My graphic card is a NVIDIA GeForce GTX 750 Ti with 2 GB of VRAM: is there a configuration that allows to use the model with this amount of VRAM ?

**Comment by adamian98** [comment]
Unfortunately 2GB is not enough memory to store all of the gradients necessary during optimization. We ran our tests with 8GB of memory but I believe that you should be able to run the code with 4GB as well.
