### ISSUE TITLE
MAC OX CUDA issuse

### ISSUE THREAD

**Issue by iushas** [adamian98/pulse#13]
Platform: macbook pro 16in
AssertionError: Torch not compiled with CUDA enabled

![image](https://user-images.githubusercontent.com/7236171/85108195-e0a8d200-b241-11ea-9fb7-2902f80c920a.png)

**Comment by sachit-menon** [comment]
The code only supports machines with CUDA-enabled GPUs. Apple has not included NVIDIA GPUs in most MacBooks and they are thus not CUDA supported.
