### ISSUE TITLE
Training and Inferencing documentation

### ISSUE THREAD

**Issue by deepseek** [adamian98/pulse#18]
@adamian98 @georgzoeller 
Hi there,

- it's would be great to know how to train pulse from scratch
- Also how to use the trained model to inference
- Note that the download links have reached a daily quota, so you might want to upload the files into a multiple services, example: gdrive, onedrive, dropbox, etc..

**Comment by AndrewAF1** [comment]
I second the part about training - I'd love to train a model with different data for some experiments.

**Comment by coloneldbugger** [comment]
@deepseek I'm thinking that we can train our own StyleGAN models using NVidia's StyleGAN repo.  I have asked for confirmation in another thread that a custom trained StyleGAN model will snap-in and work. I'm going to see if I can get it working with a pretrained model from another source to test it out.  It would be really nice if StyleGAN2 worked as well but I doubt that will just work out of the box.

You can use your personal Google account to copy files to your own GDrive to bypass quotas.  It's a bit of a pain in the ass sometimes for an automated workflow like this is attempting to do but it's a work around that will get you the file you need.

**Comment by AndroYD84** [comment]
I second the request as well, I'd like to train this with aligned full bodies on a green screen, do you think it's worth trying or there's no chance it may actually work? It's definitely more complex than doing it on faces alone.

**Comment by 0xinit** [comment]
I am looking for training process as well. @sachit-menon , @adamian98 , of course you don't need to, but do guys think you can help us out here a bit? 

Thanks,
Gaurav
