### ISSUE TITLE
WebApp again?

### ISSUE THREAD

**Issue by chstdu** [adamian98/pulse#28]
Unfortunately I don't have a GPU. Thus, I would like to suggest to bring back the web app for people to directly try pulse. Any chances?

**Comment by attilaolah** [comment]
You can probably still run it with Google Colab using a free GPU runtime, although it would be nice to have a ready-made notebook for that.

**Comment by attilaolah** [comment]
Turns out there is actually a Colab already, over at https://github.com/tg-bomze/Face-Depixelizer, maybe try that.

**Comment by chstdu** [comment]
Thank you for the link. When trying, I receive the attached error message. Is this because of the mentioned daily capacity constraints or does my (pixelated) face happen to be just too crazy?

```
Loading Synthesis Network
Downloading https://drive.google.com/uc?id=1TCViX1YpQyRsklTVYEJwdbmK91vklCo8 ... done
Optimizing
BEST (100) | L2: 0.0040 | GEOCROSS: 5.7679 | TOTAL: 0.6895 | time: 58.1 | it/s: 1.72 | batchsize: 1
Could not find a face that downscales correctly within epsilon
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-af0d780e3ec8> in <module>()
     90 ax1.imshow(mpimg.imread('/content/pulse/input/face.png'))
     91 ax1.set_title('Original')
---> 92 ax2.imshow(mpimg.imread('/content/pulse/runs/face.png'))
     93 ax2.set_title('Result')
     94 plt.show()

3 frames
/usr/local/lib/python3.6/dist-packages/matplotlib/cbook/__init__.py in to_filehandle(fname, flag, return_opened, encoding)
    401             fh = bz2.BZ2File(fname, flag)
    402         else:
--> 403             fh = open(fname, flag, encoding=encoding)
    404         opened = True
    405     elif hasattr(fname, 'seek'):

FileNotFoundError: [Errno 2] No such file or directory: '/content/pulse/runs/face.png'
```

**Comment by Acurisu** [comment]
This issue has been addressed in both this repository ([see](https://github.com/adamian98/pulse/issues/19)) and over at tg-bomze/Face-Depixelizer ([see](https://github.com/tg-bomze/Face-Depixelizer/issues/7)).

**Comment by chstdu** [comment]
Okay. Now I am getting the "Google Drive quota exceeded" error. Thus, I will try again tomorrow and with more steps. Strange that Google imposes quotas / restrictions while heavily advocating for AI themselves.
