### ISSUE TITLE
What time does the quota reset?

### ISSUE THREAD

**Issue by mesqueeb** [adamian98/pulse#5]
I have been trying to test a single photo for a couple of days now, but the quota is always exceeded.

What is the time (+timezone) the daily quota resets? This way I can try again right at that moment.

Best regards

**Comment by sachit-menon** [comment]
Hi, many people have been having this issue - unfortunately Google resets it 24 hours after the quota is hit, so it varies based on how early the quota was hit in the day. Wish I had a clearer answer for you, sorry! Google Drive sets the cutoffs, not us.
