### ISSUE TITLE
Can I transfer my own stylegan model?

### ISSUE THREAD

**Issue by CheungYuHui** [adamian98/pulse#57]
I had trained my own stylegan model, and convert the pkl file to pt format by using stylegan-pytorch project.
But when I run PULSE, it come up with some errors as follow:

Loading Synthesis Network
Traceback (most recent call last):
  File "run.py", line 58, in <module>
    model = PULSE(cache_dir=kwargs["cache_dir"])
  File "H:\Pulse\PULSE.py", line 25, in __init__
    self.synthesis.load_state_dict(torch.load("./models/karras2019stylegan-ffhq-1024x1024.for_g_all.pt"))
  File "D:\Anaconda3\envs\pulse\lib\site-packages\torch\nn\modules\module.py", line 846, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for G_synthesis:
        Missing key(s) in state_dict: "torgb.weight", "torgb.bias", "blocks.4x4.const", "blocks.4x4.bias", "blocks.4x4.epi1.noise.weight", "blocks.4x4.epi1.style_mod.lin.weight", "blocks.4x4.epi1.style_mod.lin.bias", "blocks.4x4.conv.weight", "blocks.4x4.conv.bias", "blocks.4x4.epi2.noise.weight", "blocks.4x4.epi2.style_mod.lin.weight", "blocks.4x4.epi2.style_mod.lin.bias", "blocks.8x8.conv0_up.weight", "blocks.8x8.conv0_up.bias", "blocks.8x8.conv0_up.intermediate.kernel", "blocks.8x8.epi1.noise.weight", "blocks.8x8.epi1.style_mod.lin.weight", "blocks.8x8.epi1.style_mod.lin.bias", "blocks.8x8.conv1.weight", "blocks.8x8.conv1.bias", "blocks.8x8.epi2.noise.weight", "blocks.8x8.epi2.style_mod.lin.weight", "blocks.8x8.epi2.style_mod.lin.bias", "blocks.16x16.conv0_up.weight", "blocks.16x16.conv0_up.bias", "blocks.16x16.conv0_up.intermediate.kernel", "blocks.16x16.epi1.noise.weight", "blocks.16x16.epi1.style_mod.lin.weight", "blocks.16x16.epi1.style_mod.lin.bias", "blocks.16x16.conv1.weight", "blocks.16x16.conv1.bias", "blocks.16x16.epi2.noise.weight", "blocks.16x16.epi2.style_mod.lin.weight", "blocks.16x16.epi2.style_mod.lin.bias", "blocks.32x32.conv0_up.weight", "blocks.32x32.conv0_up.bias", "blocks.32x32.conv0_up.intermediate.kernel", "blocks.32x32.epi1.noise.weight", "blocks.32x32.epi1.style_mod.lin.weight", "blocks.32x32.epi1.style_mod.lin.bias", "blocks.32x32.conv1.weight", "blocks.32x32.conv1.bias", "blocks.32x32.epi2.noise.weight", "blocks.32x32.epi2.style_mod.lin.weight", "blocks.32x32.epi2.style_mod.lin.bias", "blocks.64x64.conv0_up.weight", "blocks.64x64.conv0_up.bias", "blocks.64x64.conv0_up.intermediate.kernel", "blocks.64x64.epi1.noise.weight", "blocks.64x64.epi1.style_mod.lin.weight", "blocks.64x64.epi1.style_mod.lin.bias", "blocks.64x64.conv1.weight", "blocks.64x64.conv1.bias", "blocks.64x64.epi2.noise.weight", "blocks.64x64.epi2.style_mod.lin.weight", "blocks.64x64.epi2.style_mod.lin.bias", "blocks.128x128.conv0_up.weight", "blocks.128x128.conv0_up.bias", "blocks.128x128.conv0_up.intermediate.kernel", "blocks.128x128.epi1.noise.weight", "blocks.128x128.epi1.style_mod.lin.weight", "blocks.128x128.epi1.style_mod.lin.bias", "blocks.128x128.conv1.weight", "blocks.128x128.conv1.bias", "blocks.128x128.epi2.noise.weight", "blocks.128x128.epi2.style_mod.lin.weight", "blocks.128x128.epi2.style_mod.lin.bias", "blocks.256x256.conv0_up.weight", "blocks.256x256.conv0_up.bias", "blocks.256x256.conv0_up.intermediate.kernel", "blocks.256x256.epi1.noise.weight", "blocks.256x256.epi1.style_mod.lin.weight", "blocks.256x256.epi1.style_mod.lin.bias", "blocks.256x256.conv1.weight", "blocks.256x256.conv1.bias", "blocks.256x256.epi2.noise.weight", "blocks.256x256.epi2.style_mod.lin.weight", "blocks.256x256.epi2.style_mod.lin.bias", "blocks.512x512.conv0_up.weight", "blocks.512x512.conv0_up.bias", "blocks.512x512.conv0_up.intermediate.kernel", "blocks.512x512.epi1.noise.weight", "blocks.512x512.epi1.style_mod.lin.weight", "blocks.512x512.epi1.style_mod.lin.bias", "blocks.512x512.conv1.weight", "blocks.512x512.conv1.bias", "blocks.512x512.epi2.noise.weight", "blocks.512x512.epi2.style_mod.lin.weight", "blocks.512x512.epi2.style_mod.lin.bias", "blocks.1024x1024.conv0_up.weight", "blocks.1024x1024.conv0_up.bias", "blocks.1024x1024.conv0_up.intermediate.kernel", "blocks.1024x1024.epi1.noise.weight", "blocks.1024x1024.epi1.style_mod.lin.weight", "blocks.1024x1024.epi1.style_mod.lin.bias", "blocks.1024x1024.conv1.weight", "blocks.1024x1024.conv1.bias", "blocks.1024x1024.epi2.noise.weight", "blocks.1024x1024.epi2.style_mod.lin.weight", "blocks.1024x1024.epi2.style_mod.lin.bias".
        Unexpected key(s) in state_dict: "g_mapping.dense0.weight", "g_mapping.dense0.bias", "g_mapping.dense1.weight", "g_mapping.dense1.bias", "g_mapping.dense2.weight", "g_mapping.dense2.bias", "g_mapping.dense3.weight", "g_mapping.dense3.bias", "g_mapping.dense4.weight", "g_mapping.dense4.bias", "g_mapping.dense5.weight", "g_mapping.dense5.bias", "g_mapping.dense6.weight", "g_mapping.dense6.bias", "g_mapping.dense7.weight", "g_mapping.dense7.bias", "g_synthesis.torgb.weight", "g_synthesis.torgb.bias", "g_synthesis.blocks.4x4.const", "g_synthesis.blocks.4x4.bias", "g_synthesis.blocks.4x4.epi1.top_epi.noise.weight", "g_synthesis.blocks.4x4.epi1.style_mod.lin.weight", "g_synthesis.blocks.4x4.epi1.style_mod.lin.bias", "g_synthesis.blocks.4x4.conv.weight", "g_synthesis.blocks.4x4.conv.bias", "g_synthesis.blocks.4x4.epi2.top_epi.noise.weight", "g_synthesis.blocks.4x4.epi2.style_mod.lin.weight", "g_synthesis.blocks.4x4.epi2.style_mod.lin.bias", "g_synthesis.blocks.8x8.conv0_up.weight", "g_synthesis.blocks.8x8.conv0_up.bias", "g_synthesis.blocks.8x8.conv0_up.intermediate.kernel", "g_synthesis.blocks.8x8.epi1.top_epi.noise.weight", "g_synthesis.blocks.8x8.epi1.style_mod.lin.weight", "g_synthesis.blocks.8x8.epi1.style_mod.lin.bias", "g_synthesis.blocks.8x8.conv1.weight", "g_synthesis.blocks.8x8.conv1.bias", "g_synthesis.blocks.8x8.epi2.top_epi.noise.weight", "g_synthesis.blocks.8x8.epi2.style_mod.lin.weight", "g_synthesis.blocks.8x8.epi2.style_mod.lin.bias", "g_synthesis.blocks.16x16.conv0_up.weight", "g_synthesis.blocks.16x16.conv0_up.bias", "g_synthesis.blocks.16x16.conv0_up.intermediate.kernel", "g_synthesis.blocks.16x16.epi1.top_epi.noise.weight", "g_synthesis.blocks.16x16.epi1.style_mod.lin.weight", "g_synthesis.blocks.16x16.epi1.style_mod.lin.bias", "g_synthesis.blocks.16x16.conv1.weight", "g_synthesis.blocks.16x16.conv1.bias", "g_synthesis.blocks.16x16.epi2.top_epi.noise.weight", "g_synthesis.blocks.16x16.epi2.style_mod.lin.weight", "g_synthesis.blocks.16x16.epi2.style_mod.lin.bias", "g_synthesis.blocks.32x32.conv0_up.weight", "g_synthesis.blocks.32x32.conv0_up.bias", "g_synthesis.blocks.32x32.conv0_up.intermediate.kernel", "g_synthesis.blocks.32x32.epi1.top_epi.noise.weight", "g_synthesis.blocks.32x32.epi1.style_mod.lin.weight", "g_synthesis.blocks.32x32.epi1.style_mod.lin.bias", "g_synthesis.blocks.32x32.conv1.weight", "g_synthesis.blocks.32x32.conv1.bias", "g_synthesis.blocks.32x32.epi2.top_epi.noise.weight", "g_synthesis.blocks.32x32.epi2.style_mod.lin.weight", "g_synthesis.blocks.32x32.epi2.style_mod.lin.bias", "g_synthesis.blocks.64x64.conv0_up.weight", "g_synthesis.blocks.64x64.conv0_up.bias", "g_synthesis.blocks.64x64.conv0_up.intermediate.kernel", "g_synthesis.blocks.64x64.epi1.top_epi.noise.weight", "g_synthesis.blocks.64x64.epi1.style_mod.lin.weight", "g_synthesis.blocks.64x64.epi1.style_mod.lin.bias", "g_synthesis.blocks.64x64.conv1.weight", "g_synthesis.blocks.64x64.conv1.bias", "g_synthesis.blocks.64x64.epi2.top_epi.noise.weight", "g_synthesis.blocks.64x64.epi2.style_mod.lin.weight", "g_synthesis.blocks.64x64.epi2.style_mod.lin.bias", "g_synthesis.blocks.128x128.conv0_up.weight", "g_synthesis.blocks.128x128.conv0_up.bias", "g_synthesis.blocks.128x128.conv0_up.intermediate.kernel", "g_synthesis.blocks.128x128.epi1.top_epi.noise.weight", "g_synthesis.blocks.128x128.epi1.style_mod.lin.weight", "g_synthesis.blocks.128x128.epi1.style_mod.lin.bias", "g_synthesis.blocks.128x128.conv1.weight", "g_synthesis.blocks.128x128.conv1.bias", "g_synthesis.blocks.128x128.epi2.top_epi.noise.weight", "g_synthesis.blocks.128x128.epi2.style_mod.lin.weight", "g_synthesis.blocks.128x128.epi2.style_mod.lin.bias", "g_synthesis.blocks.256x256.conv0_up.weight", "g_synthesis.blocks.256x256.conv0_up.bias", "g_synthesis.blocks.256x256.conv0_up.intermediate.kernel", "g_synthesis.blocks.256x256.epi1.top_epi.noise.weight", "g_synthesis.blocks.256x256.epi1.style_mod.lin.weight", "g_synthesis.blocks.256x256.epi1.style_mod.lin.bias", "g_synthesis.blocks.256x256.conv1.weight", "g_synthesis.blocks.256x256.conv1.bias", "g_synthesis.blocks.256x256.epi2.top_epi.noise.weight", "g_synthesis.blocks.256x256.epi2.style_mod.lin.weight", "g_synthesis.blocks.256x256.epi2.style_mod.lin.bias", "g_synthesis.blocks.512x512.conv0_up.weight", "g_synthesis.blocks.512x512.conv0_up.bias", "g_synthesis.blocks.512x512.conv0_up.intermediate.kernel", "g_synthesis.blocks.512x512.epi1.top_epi.noise.weight", "g_synthesis.blocks.512x512.epi1.style_mod.lin.weight", "g_synthesis.blocks.512x512.epi1.style_mod.lin.bias", "g_synthesis.blocks.512x512.conv1.weight", "g_synthesis.blocks.512x512.conv1.bias", "g_synthesis.blocks.512x512.epi2.top_epi.noise.weight", "g_synthesis.blocks.512x512.epi2.style_mod.lin.weight", "g_synthesis.blocks.512x512.epi2.style_mod.lin.bias", "g_synthesis.blocks.1024x1024.conv0_up.weight", "g_synthesis.blocks.1024x1024.conv0_up.bias", "g_synthesis.blocks.1024x1024.conv0_up.intermediate.kernel", "g_synthesis.blocks.1024x1024.epi1.top_epi.noise.weight", "g_synthesis.blocks.1024x1024.epi1.style_mod.lin.weight", "g_synthesis.blocks.1024x1024.epi1.style_mod.lin.bias", "g_synthesis.blocks.1024x1024.conv1.weight", "g_synthesis.blocks.1024x1024.conv1.bias", "g_synthesis.blocks.1024x1024.epi2.top_epi.noise.weight", "g_synthesis.blocks.1024x1024.epi2.style_mod.lin.weight", "g_synthesis.blocks.1024x1024.epi2.style_mod.lin.bias".

So, is there any way that I can make it right?
FULLY RESPECT.

**Comment by sweihub** [comment]
都是中国人在玩，哈哈，直接中文吧。
貌似作者的StyleGAN模型有自己改动过，所以官方的模型转换过来有问题。

**Comment by CheungYuHui** [comment]
> 都是中国人在玩，哈哈，直接中文吧。
> 貌似作者的StyleGAN模型有自己改动过，所以官方的模型转换过来有问题。

翻了论文，怎么转换一笔带过了，没办法只能来问了

**Comment by sweihub** [comment]
把StyleGAN直接替换成StyleGAN2-PyTorch应该可行，我之前把 DGP (Deep Generator Prior)的BigGAN换成StyleGAN2，不过效果不理想。 PULSE通过把  -num_trainable_noise_layers 参数设置为20，输入图片尺寸提高到256x256，我还加入了人脸比对损失，可以强制拟合西方人脸到东人方脸，不过细节不行。以下是从256x256到1024x1024的超分辨率效果。

LR1
![liuyifei1_256](https://user-images.githubusercontent.com/5334841/90970297-b7ecd380-e535-11ea-893e-4ce2c6e91ade.png)

HR1
![liuyifei1_1024](https://user-images.githubusercontent.com/5334841/90970300-be7b4b00-e535-11ea-9f36-49f805efe610.png)

LR2
![liuyifei2_256](https://user-images.githubusercontent.com/5334841/90970301-c4712c00-e535-11ea-9a12-87ef13fe69c0.png)

HR2
![liuyifei2_1024](https://user-images.githubusercontent.com/5334841/90970302-c6d38600-e535-11ea-8409-5d90e78ad5da.png)

**Comment by sweihub** [comment]
可以试试我加强的代码，暂时还是用StyleGAN，打算后面替换成StyleGAN2。

EPULSE: Enahnced PULSE
https://github.com/sweihub/epulse

**Comment by CheungYuHui** [comment]
> 可以试试我加强的代码，暂时还是用StyleGAN，打算后面替换成StyleGAN2。
> 
> EPULSE: Enahnced PULSE
> https://github.com/sweihub/epulse

本不抱希望，没想真有大神，感谢慷慨分享，我去细瞧点赞。

**Comment by CheungYuHui** [comment]
> 可以试试我加强的代码，暂时还是用StyleGAN，打算后面替换成StyleGAN2。
> 
> EPULSE: Enahnced PULSE
> https://github.com/sweihub/epulse

另外，一开始我也试了用stylgan2-pytorch转换的二代模型，出现的错误也是类似的。
