### ISSUE TITLE
illegal hardware instruction In Apple Arm64 

### ISSUE THREAD

**Issue by zephyrpathsofglory** [adamian98/pulse#70]
I have done everything needed, then run `python run.py`, and the only output is `[1]    36213 illegal hardware instruction  python run.py`.

Did not it support in Apple Arm64 architecture?

**Comment by powerpuffmatt** [comment]
Seeing that the readme was last edited 7 months ago and it says "Currently the code only works with CUDA installed (and therefore requires an appropriate GPU) and has been tested on Linux and Windows" it doesnt look like it will work. 

According to offical documentation by nvidia, you not only need an nvidia gpu but also "The CUDA Development Tools require an **Intel-based Mac** running Mac OSX v. 10.8 or later." (http://developer.download.nvidia.com/compute/cuda/6_5/rel/docs/CUDA_Getting_Started_Mac.pdf) 

I dont expect it to come later either read here -> https://www.provideocoalition.com/officially-official-nvidia-drops-cuda-support-for-macos/ 

Sorry mate. Arm is really awesome though and so are those new macs! I hope this changes in the future. 

The one saving grace is that older macs theoretically work with an nvidia gpu if you have one kicking around and are willing to put aside some time to tinker and find drivers. You could theoretically run a virtual environment of linux or windows on said machines if needed but I would make sure that your gpu has a good amount of vram before attempting this. I've seen this program needs for sure 4gb and maybe up to 8gb to run. I wish I had real world testing to give you a solid number on that.

**Comment by zephyrpathsofglory** [comment]
Sorry for this stupid question, I am so ignorant about image process and I have not read the README carefully. I will close it.
